package:
  name: bolt-lmm-genetic-map-hg38
  version: "v2.3.4"

source:
  url: https://storage.googleapis.com/broad-alkesgroup-public/BOLT-LMM/downloads/BOLT-LMM_v2.3.4.tar.gz

about:
  home: https://alkesgroup.broadinstitute.org/BOLT-LMM
